# Generated by Django 4.2.28 on 2026-02-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_project', '0003_notification'),
        ('attendance_project', '0004_auditlog'),
    ]

    operations = [
    ]
